source:      .
package_version: 0.1.0
baseurl: /buster-cljs.docs
url: http://localhost:4000
destination: ./_site
plugins:     ./_plugins
auto: true
exclude: [bin, CNAME, Gemfile, Gemfile.lock, README.md]
markdown: rdiscount
permalink: /:title
